<?php

$keys = [];

$keys["projects"] = [];
$keys["projects"]["team"] = [];
$keys["projects"]["projects"] = [];
$keys["network"] = [];
$keys["network"]["people"] = [];
$keys["network"]["projects"] = [];
$keys["projects"]["suites"] = [];
$keys["projects"]["tests"] = [];

$keys["projects"]["team"]["remove_member"] = 
					[ 
						"name" => "Remove Member", 
						"message" => "You're not allowed to remove team members from this project.", 
						"keywords" => "unassign remove delete team member", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["edit_member"] = 
					[ 
						"name" => "Edit Member", 
						"message" => "You're not allowed to modify access rights for team members on this project.", 
						"keywords" => "edit change update team member permissions", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["add_member"] = 
					[ 
						"name" => "Add Member", 
						"message" => "You're not allowed to add team members to this project.", 
						"keywords" => "assign add team member", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["view_members"] = 
					[ 
						"name" => "View Members", 
						"message" => "You're not allowed to view team members on this project.", 
						"keywords" => "view list team members", 
						"access_type" => "r" 
					];

$keys["projects"]["projects"]["view_properties"] = 
					[ 
						"name" => "View Project Properties", 
						"message" => "You're not allowed to view properties on this project's dashboard.", 
						"keywords" => "view dashboard properties project", 
						"access_type" => "r" 
					];

$keys["projects"]["projects"]["view_all_activities"] = 
					[ 
						"name" => "View All Activities", 
						"message" => "You're not allowed to view activities on this project that were not generated by you.", 
						"keywords" => "view project dashboard activity activities feed", 
						"access_type" => "r" 
					];

$keys["projects"]["projects"]["view_activities"] = 
					[ 
						"name" => "View Activities", 
						"message" => "You're not allowed to view activities on the project dashboard.", 
						"keywords" => "view project dashboard activity activities feed", 
						"access_type" => "r" 
					];

$keys["projects"]["projects"]["view_dashboard"] = 
					[ 
						"name" => "View Project Dashboard", 
						"message" => "You're not allowed to view the project dashboard.", 
						"keywords" => "view project dashboard", 
						"access_type" => "r" 
					];

$keys["projects"]["projects"]["view_details"] = 
					[ 
						"name" => "View Project Details", 
						"message" => "You're not allowed to view project details.", 
						"keywords" => "view project details information", 
						"access_type" => "r" 
					];

$keys["projects"]["projects"]["update_project"] = 
					[ 
						"name" => "Update Project Details", 
						"message" => "You're not allowed to update project details.", 
						"keywords" => "edit update change project details", 
						"access_type" => "w" 
					];

$keys["network"]["people"]["remove_person"] = 
					[ 
						"name" => "Remove a Person", 
						"message" => "You're not allowed to remove a person from this network.", 
						"keywords" => "delete remove person", 
						"access_type" => "w" 
					];

$keys["network"]["people"]["update_person"] = 
					[ 
						"name" => "Update a Person", 
						"message" => "You're not allowed update a person in the network.", 
						"keywords" => "update edit change person", 
						"access_type" => "w" 
					];

$keys["network"]["people"]["create_person"] = 
					[ 
						"name" => "Invite a Person", 
						"message" => "You're not allowed to create a person in this network.", 
						"keywords" => "add new create person network", 
						"access_type" => "w" 
					];

$keys["network"]["people"]["view_people"] = 
					[ 
						"name" => "View People", 
						"message" => "You're not allowed to view people in this network.", 
						"keywords" => "view list network people", 
						"access_type" => "r" 
					];

$keys["network"]["projects"]["own_projects"] = 
					[ 
						"name" => "Own Projects", 
						"message" => "You're not allowed to own projects.", 
						"keywords" => "own project", 
						"access_type" => "w" 
					];

$keys["network"]["projects"]["create_project"] = 
					[ 
						"name" => "Create Projects", 
						"message" => "You're not allowed to create projects.", 
						"keywords" => "create add new project", 
						"access_type" => "w" 
					];

$keys["network"]["projects"]["view_projects"] = 
					[ 
						"name" => "View Projects", 
						"message" => "You're not allowed to view projects in this network.", 
						"keywords" => "view project list", 
						"access_type" => "r" 
					];

$keys["projects"]["team"]["update_member_restrictions"] = 
					[ 
						"name" => "Update Member's Restrictions", 
						"message" => "You're not allowed to change restriction access for team members on this project.", 
						"keywords" => "update change edit modify member restrictions team", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["view_member_restrictions"] = 
					[ 
						"name" => "View Member's Restrictions", 
						"message" => "You're not allowed to view restriction access settings for team members on this project.", 
						"keywords" => "view member restrictions team", 
						"access_type" => "r" 
					];

$keys["projects"]["team"]["update_member_overrides"] = 
					[ 
						"name" => "Update Member's Overrides", 
						"message" => "You're not allowed to change override access for team members on this project.", 
						"keywords" => "update modify change edit member permissions overrides team", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["view_member_overrides"] = 
					[ 
						"name" => "View Member's Overrides", 
						"message" => "You're not allowed to view override access settings for team members on this project.", 
						"keywords" => "view member permissions overrides team", 
						"access_type" => "r" 
					];

$keys["projects"]["team"]["update_member_roles"] = 
					[ 
						"name" => "Update Member's Roles", 
						"message" => "You're not allowed to change roles for team members on this project.", 
						"keywords" => "update change edit modify member role team", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["view_member_roles"] = 
					[ 
						"name" => "View Member's Roles", 
						"message" => "You're not allowed to view roles in this project.", 
						"keywords" => "view team member roles", 
						"access_type" => "r" 
					];

$keys["projects"]["team"]["view_member"] = 
					[ 
						"name" => "View Member", 
						"message" => "You're not allowed to view team members on this project.", 
						"keywords" => "view team member", 
						"access_type" => "r" 
					];

$keys["projects"]["team"]["update_member"] = 
					[ 
						"name" => "Update Member", 
						"message" => "You're not allowed to change access settings for team members on this project.", 
						"keywords" => "update edit modify change team member", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["update_role_permissions"] = 
					[ 
						"name" => "Update Roles", 
						"message" => "You're not allowed to change permissions for team members on this project.", 
						"keywords" => "change edit update modify team role", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["view_role_permissions"] = 
					[ 
						"name" => "View Role Permissions", 
						"message" => "You're not allowed to view permissions for team members on this project.", 
						"keywords" => "view role permission access team", 
						"access_type" => "r" 
					];

$keys["projects"]["team"]["view_role"] = 
					[ 
						"name" => "View Role", 
						"message" => "You're not allowed to view roles for team members on this project.", 
						"keywords" => "view role team", 
						"access_type" => "r" 
					];

$keys["projects"]["team"]["update_role"] = 
					[ 
						"name" => "Update Roles", 
						"message" => "You're not allowed to change roles for team members on this project.", 
						"keywords" => "update change edit role team", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["create_role"] = 
					[ 
						"name" => "Create Roles", 
						"message" => "You're not allowed to create roles for team members on this project.", 
						"keywords" => "create add new role team", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["view_roles"] = 
					[ 
						"name" => "View Roles", 
						"message" => "You're not allowed to view roles for team members on this project.", 
						"keywords" => "view member roles", 
						"access_type" => "r" 
					];

$keys["network"]["projects"]["view_all_projects"] = 
					[ 
						"name" => "View All Projects", 
						"message" => "You're not allowed to view projects in this network that were created by others.", 
						"keywords" => "view project list", 
						"access_type" => "r" 
					];

$keys["projects"]["projects"]["exclusive_access"] = 
					[ 
						"name" => "Exclusive Access", 
						"message" => "You do not have enough permissions.", 
						"keywords" => "administrator exclusive full access", 
						"access_type" => "w" 
					];

$keys["projects"]["projects"]["project_admin"] = 
					[ 
						"name" => "Project Admin", 
						"message" => "You do not have enough permissions.", 
						"keywords" => "project team super admin", 
						"access_type" => "w" 
					];

$keys["projects"]["team"]["view_deleted_members"] = 
					[ 
						"name" => "View Deleted Members", 
						"message" => "You're not allowed to remove members from this project's team.", 
						"keywords" => "project team member delete remove suspend", 
						"access_type" => "r" 
					];

$keys["projects"]["suites"]["view_suites"] = 
					[ 
						"name" => "View Test Suites", 
						"message" => "You're not allowed to view test suites.", 
						"keywords" => "project test suites", 
						"access_type" => "r" 
					];

$keys["projects"]["suites"]["view_all_suites"] = 
					[ 
						"name" => "View Any Test Suite", 
						"message" => "You're not allowed to view test suites created by others.", 
						"keywords" => "project test suites", 
						"access_type" => "r" 
					];

$keys["projects"]["suites"]["create_suite"] = 
					[ 
						"name" => "Create Test Suite", 
						"message" => "You're not allowed to create test suites in this project.", 
						"keywords" => "project add new create test suite", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["update_suites"] = 
					[ 
						"name" => "Update Test Suites", 
						"message" => "You're not allowed to update test suites created by others.", 
						"keywords" => "project modify update change edit test suite", 
						"access_type" => "w" 
					];

$keys["projects"]["projects"]["update_all_projects"] = 
					[ 
						"name" => "Update All Projects", 
						"message" => "You're not allowed to update projects created by others.", 
						"keywords" => "edit update change project details", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["delete_suite"] = 
					[ 
						"name" => "Delete Test Suite", 
						"message" => "You're not allowed to delete test suites.", 
						"keywords" => "project delete move test suites", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["delete_all_suites"] = 
					[ 
						"name" => "Delete Any Test Suite", 
						"message" => "You're not allowed to delete test suites created by others.", 
						"keywords" => "project delete move test suites", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["copy_suite"] = 
					[ 
						"name" => "Copy Test Suite", 
						"message" => "You're not allowed to copy test suites.", 
						"keywords" => "project duplicate copy test suites", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["copy_all_suites"] = 
					[ 
						"name" => "Copy Any Test Suite", 
						"message" => "You're not allowed to copy test suites that were created by others.", 
						"keywords" => "project duplicate copy test suites", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["create_scenario"] = 
					[ 
						"name" => "Create Test Scenario", 
						"message" => "You're not allowed to create test scenarios.", 
						"keywords" => "project scenario add create new test suites", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["update_scenarios"] = 
					[ 
						"name" => "Update Test Scenarios", 
						"message" => "You're not allowed to update test scenarios created by others.", 
						"keywords" => "project edit update modify change test scenarios", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["delete_scenario"] = 
					[ 
						"name" => "Delete Test Scenario", 
						"message" => "You're not allowed to delete test scenarios.", 
						"keywords" => "project delete remove test scenarios", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["delete_all_scenarios"] = 
					[ 
						"name" => "Delete Any Test Scenario", 
						"message" => "You're not allowed to delete test scenarios created by others.", 
						"keywords" => "project delete remove test scenarios", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["create_case"] = 
					[ 
						"name" => "Create Test Case", 
						"message" => "You're not allowed to create or update test cases.", 
						"keywords" => "project create add new test case", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["update_cases"] = 
					[ 
						"name" => "Update Test Cases", 
						"message" => "You're not allowed to update test cases created by others.", 
						"keywords" => "project update modify edit change test case", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["delete_case"] = 
					[ 
						"name" => "Delete Test Case", 
						"message" => "You're not allowed to delete test cases.", 
						"keywords" => "project delete remove test cases", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["delete_all_cases"] = 
					[ 
						"name" => "Delete Any Test Case", 
						"message" => "You're not allowed to delete test cases created by others.", 
						"keywords" => "project delete remove test cases", 
						"access_type" => "w" 
					];

$keys["projects"]["suites"]["view_scenarios"] = 
					[ 
						"name" => "View Test Scenarios", 
						"message" => "You're not allowed to view test scenarios.", 
						"keywords" => "view open test scenarios", 
						"access_type" => "r" 
					];

$keys["projects"]["suites"]["view_all_scenarios"] = 
					[ 
						"name" => "View Any Test Scenario", 
						"message" => "You're not allowed to view test scenarios created by others.", 
						"keywords" => "view open test scenarios", 
						"access_type" => "r" 
					];

$keys["projects"]["suites"]["view_cases"] = 
					[ 
						"name" => "View Test Cases", 
						"message" => "You're not allowed to view test cases.", 
						"keywords" => "view open test cases", 
						"access_type" => "r" 
					];

$keys["projects"]["suites"]["view_all_cases"] = 
					[ 
						"name" => "View Any Test Case", 
						"message" => "You're not allowed to view test cases created by others.", 
						"keywords" => "view open test cases", 
						"access_type" => "r" 
					];

$keys["projects"]["tests"]["tester"] = 
					[ 
						"name" => "Tester", 
						"message" => "You're not allowed to test this project.", 
						"keywords" => "test run execute tester", 
						"access_type" => "w" 
					];

$keys["projects"]["tests"]["view_tests"] = 
					[ 
						"name" => "View Tests", 
						"message" => "You're not allowed to view test runs.", 
						"keywords" => "view open test runs", 
						"access_type" => "r" 
					];

$keys["projects"]["tests"]["edit_test"] = 
					[ 
						"name" => "Edit test", 
						"message" => "You're not allowed to edit test runs.", 
						"keywords" => "edit modify update change test run", 
						"access_type" => "w" 
					];

$keys["projects"]["tests"]["view_batches"] = 
					[ 
						"name" => "View Batches", 
						"message" => "You're not allowed to view test run batches.", 
						"keywords" => "view test run batches", 
						"access_type" => "r" 
					];

$keys["projects"]["tests"]["start_batch"] = 
					[ 
						"name" => "Start Batch", 
						"message" => "You're not allowed to start a test run batch.", 
						"keywords" => "start test run batch", 
						"access_type" => "w" 
					];

$keys["projects"]["tests"]["stop_batch"] = 
					[ 
						"name" => "Stop Batch", 
						"message" => "You're not allowed to stop a test run batch.", 
						"keywords" => "stop test run batch", 
						"access_type" => "w" 
					];

$keys["projects"]["tests"]["create_test"] = 
					[ 
						"name" => "Create Test", 
						"message" => "You're not allowed to create tests.", 
						"keywords" => "create new add test run", 
						"access_type" => "w" 
					];

$keys["projects"]["tests"]["view_test_results"] = 
					[ 
						"name" => "View Test Results", 
						"message" => "You're not allowed to view test results.", 
						"keywords" => "test results", 
						"access_type" => "r" 
					];

$keys["network"]["people"]["network_owner"] = 
					[ 
						"name" => "Network Owner", 
						"message" => "You do not have enough permissions to proceed.", 
						"keywords" => "owner administrator", 
						"access_type" => "w" 
					];

$keys["projects"]["tests"]["create_issue"] = 
					[ 
						"name" => "Create Issue", 
						"message" => "You're not allowed to create new issues.", 
						"keywords" => "create add new test issue", 
						"access_type" => "w" 
					];



	return $keys;